name = "BuoyQC"
uuid = "f054d67f-f98f-4575-8066-61bd4663fe05"
authors = ["Kosuke Sando <kosukesando@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
